Replace force_text with force_str
django-cms/djangocms-text-ckeditor pull request #546
Opened 2020-10-15 08:21 UTC by jrief

This PR replaces the deprecated [force_text](https://docs.djangoproject.com/en/3.1/ref/utils/#django.utils.encoding.force_text) against [force_str](https://docs.djangoproject.com/en/3.1/ref/utils/#django.utils.encoding.force_str).

Since this package dropped support for Python-2 and Django<1.11, there are no compatibility issues.

2020-10-15 13:00 UTC, yakky approved these changes

2020-10-15 13:02 UTC, yakky requested changes
Maybe we should change this in tests too?

2020-10-16 09:23 UTC, jrief commented
@yakky Pps, forgot to change tests as well. Fixed now.

2020-10-16 09:25 UTC, yakky approved these changes
:+1:

2020-10-19 15:24 UTC, merged